### ISSUE TITLE
WCAG 1.3.3 Sensory Characteristics Using an image with a text alternative for graphical symbols instead of a Unicode font glyph with the desired graphical appearance but different meaning (future link) todo

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#127]
Using an image with a text alternative for graphical symbols instead of a Unicode font glyph with the desired graphical appearance but different meaning (future link) LTS Note:

**Comment by josephlabrecque** [comment]
This one is fine in the general application, but Universal Viewer does have a lot of controls with no real text... zoom, next, back, all are icons more that text.

**Comment by kimpham54** [comment]
- title attribute/tooltip on carets in facets click to expand
- search results magnifying glass button needs search

- created a ticket for universalviewer to fix settings https://github.com/UniversalViewer/universalviewer/issues/764

**Comment by jrynhart** [comment]
Add aria-label attribute to "i" element on facet panel button for screen reader "Click to expand"
Add title attribute to facet panel button for tooltip
