### ISSUE TITLE
View Details - add archivesspace ID (archival number)

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#129]
e.g. Identifier: B002.16.0202.00002 https://duarchives.coalliance.org/search?q[]=jcrs+cunningham&op[]=&field[]=keyword&from_year[]=&to_year[]=&filter_fields[]=published_agents&filter_values[]=Jewish+Consumptives%27+Relief+Society+%28U.S.%29

**Comment by jrynhart** [comment]
e8c2cb895d861585807dedbe0378e4a74e404fc4
