### ISSUE TITLE
Switch between grid and list view

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#133]

**Comment by jrynhart** [comment]
Created a grid display template for the search results. Added an option to the search url to display results in a list or grid view.  Added a dropdown select box to the search results page to set this option.

**Comment by kimpham54** [comment]
https://github.com/dulibrarytech/digitaldu-frontend/commit/bad0422810540dde59274c05619e2aa81e904f02

**Comment by jrynhart** [comment]
f2995d4d1aa495f6d2dda02b4d0cfa6462fa95c3

**Comment by jrynhart** [comment]
c44076e9a2342093bc5528543bc67ced1fab90e4
