### ISSUE TITLE
Metadata results fields

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#136]
Show title, archivesspace identifier, date, names, Second priority: subjects, notes, physical description

**Comment by jrynhart** [comment]
Removed hard coded fields from the results display, Add results metadata display to configuration.  This configuration can be updated in the future to add any required fields.  The fields to be added to the results display must exist in the object's display record

**Comment by jrynhart** [comment]
bad0422810540dde59274c05619e2aa81e904f02
