### ISSUE TITLE
Sort by field search results

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#137]
Relevancy (accurate to search term), date (chronologically ascending/descending), title (A->Z and Z->A), archivesspace identifier

**Comment by kimpham54** [comment]
mappings need to be updated on the index

**Comment by jrynhart** [comment]
Mappings do not need update; must sort on "[field].keyword"

**Comment by jrynhart** [comment]
Can sort search on non numeric field values.  Values with numeric chars and spacial chars will not sort

**Comment by kimpham54** [comment]
from kevin: do you mean by call number?
we don't need URI sorting at all, but I think sorting by call number should at least be on the road map
even if we don't have it next month


sounds like we need to be able to sort by call number, put in backlog
