### ISSUE TITLE
update error message with contact info and explanation that url may have migrated

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#167]
this is for fedora
is there a way for the repository frontend to tell when an object is compound, and display a more informative error message until we have the compound object viewer working?
like for https://specialcollections.du.edu/object/cdpsm:177 it'd be good if it told a user to contact archives@du.edu if they have questions about how to access it

not a high priority, I was just thinking about it because they got a reference question downstairs about the American Alpine Club oral histories (of which that is one)

**Comment by kimpham54** [comment]
change for new and old instance

**Comment by jrynhart** [comment]
Added the contact info message for all objects that can not be displayed

**Comment by kimpham54** [comment]
done
