### ISSUE TITLE
hide transcript from kaltura player when it's unavailable

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#172]

**Comment by jrynhart** [comment]
Always hiding the transcript viewer button for compounds that are not pdf or image.  At this point determining the compound type by mime_type.  Compound Objects of any mime type associated with audio or video objects will show the transcript button if the Kaltura player is embedded, others will not.

**Comment by jrynhart** [comment]
Mixed content compounds will require an upgrade to this functionality, eg how to identify a compound object of mixed content, what will the mime type of the compound be?

**Comment by jrynhart** [comment]
ef7a413a9f3a360c20459328806c1e72058a0f5f

**Comment by kimpham54** [comment]
closing ticket, done. won't show images now
