### ISSUE TITLE
can we use kaltura player in UV?

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#174]
need to know how to integrate kaltura into unviersalviewer, both a playlist code and a single video

**Comment by jrynhart** [comment]
Using UV compound viewer with embedded Kaltura viewer for compound objects.  No Kaltura playlist needed

**Comment by jrynhart** [comment]
Will render a compound from the index, expecting each "part" object to have an "entry_id" field

**Comment by jrynhart** [comment]
526d6b190bde00d3faae62862afea97649b4bb2b
b44da23071f09b57324342a3046c4906ce9dc414

**Comment by jackflaps** [comment]
I can’t add identifier fields at the file level in ArchivesSpace without adding properties to the file_version table, which runs the risk of breaking future upgrades

**Comment by jackflaps** [comment]
not to say it isn’t possible, but I’ll need to set up digital objects differently in the database and rewrite the API calls. this might take me a few weeks because ALA is coming up

**Comment by jrynhart** [comment]
We can also get the entry_id from the "kalturaid.txt" file.  This would take another call to the duraspace api but that is fine.  No need to add another id field

**Comment by jackflaps** [comment]
It's fine; I think the digital_object_component approach in ArchivesSpace will be easier to implement than having to generate another text file. I've got the code pretty much written already, just need to document it and run it by the archivists

**Comment by jrynhart** [comment]
Kaltura viewer iframe has been integrated into the UV player, single and compound objects.
