### ISSUE TITLE
WCAG 2.4.3 focus order - H4: Creating a logical tab order through links, form controls, and objects

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#188]

**Comment by kimpham54** [comment]
kaltura keyboard control order is annoying! jumps all over the place

**Comment by kimpham54** [comment]
tab order tested for:
- collection objects
- collections front page
- search results
- footer
- static pages
- advanced search
- search results

TODOS
- add tab index for front page facets
- add tab index for collection facets, date range works though

**Comment by jrynhart** [comment]
> kaltura keyboard control order is annoying! jumps all over the place

Need to look into updating the tab order of the embedded Kaltura viewer elements. This order can't be updated via the discovery layer
