### ISSUE TITLE
add query button is not navigable by keyboard

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#198]
https://github.com/dulibrarytech/digitaldu-frontend/blob/ee9824d898ecb9953e09777ebff1c9998c438eb1/views/advanced-search.ejs#L51

**Comment by jrynhart** [comment]
a2ea3b793cfa787e7b65f66ba8ad2ce708b33969

**Comment by kimpham54** [comment]
thanks

**Comment by kimpham54** [comment]
@jrynhart  can you add a title attribute to the button?

**Comment by kimpham54** [comment]
never mind, close ticket. you have text in the button
