### ISSUE TITLE
starting the api 

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#261]
assume transcript will be indexed in elasticsearch

phase 1
api call - GET single resource by PID
api call - GET list of items from collection URI
script -bulk grab set based on list of URIs - option to pass through CSV? or previous api list?
script - bulk grab set based on collection URI

phase 2
embed form for api query constructor. copy and paste query
zip creator

**Comment by kimpham54** [comment]
option to just get transcripts rather than entire resource?

**Comment by jrynhart** [comment]
done!
