### ISSUE TITLE
Supply back-end an endpoint used to retrieve a page used to render object viewer

### ISSUE THREAD

**Issue by freyesdulib** [dulibrarytech/digitaldu-frontend#263]
Supply back-end an HTTP endpoint used to retrieve a page containing object universal viewer.  Endpoint will check API key from back-end in order to access "private" back-end search index in order to retrieve object metadata.

**Comment by jrynhart** [comment]
d1e923562f2aa7841934f60a741af3f9054910c8
8c006904337a2a77f6d13f2a7094271fa9a833be
1d364e9e7df6a324affdb55ffb0989224e5ba962
