### ISSUE TITLE
date range placeholder

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#276]
in search facet instructions for user

**Comment by kimpham54** [comment]
ask tech services archivists if just by year is enough

**Comment by jrynhart** [comment]
Added a slider input control for to and from year values

**Comment by jrynhart** [comment]
Added a slider for from and to date inputs, await user testing

**Comment by jrynhart** [comment]
Using 1800 as default from date
Future enhancement will use earliest date in search result set
