### ISSUE TITLE
link to include suggest citation

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#277]
had that in re:discovery, had in archivesspace
automated formation of link citation

**Comment by kimpham54** [comment]
we can also mention it somewhere on the website how to cite content in the meantime
https://dp.la/item/bf8dd3ebdfdaaffb7e3fda4215d2e584?q=dog
https://www.loc.gov/resource/ppprs.00626
https://digitalcollections.nypl.org/items/510d47de-4da5-a3d9-e040-e00a18064a99

**Comment by kimpham54** [comment]
nypl: The copyright and related rights status of this item has been reviewed by The New York Public Library, but we were unable to make a conclusive determination as to the copyright status of the item. You are free to use this Item in any way that is permitted by the copyright and related rights legislation that applies to your use.

**Comment by jrynhart** [comment]
Added a citation text panel to UI, generate dynamic citations from object data. Awaiting user testing
