### ISSUE TITLE
homepage update

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#279]
- create floating box like nypl
- add message to explore X number of items, get item number from elasticsearch
- move header into box

original usability recommendation:

Use a non-serif font and a consistent color. Replace the welcome message with an action statement. "Explore ###### items digitized from Special Collections", or something like that. Change some formatting or remove white space to reduce scrolling. Use a more vidually appealing image that is either or spec coll or items from the collection.
--

**Comment by jrynhart** [comment]
Removed welcome text section from below image banner
Added floating text box to image banner, reposition title text and search form in banner
Add responsive css

**Comment by jrynhart** [comment]
*** Will replace banner image once a new one has been received from (spec coll?)
