### ISSUE TITLE
font updates

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#280]
to do release 2, footer headers will be bold. make public metadata black, make search item metadata black

Make the page title larger than sections titles. Increase line spacing. Can community and collections bolder words be turned into canned search links? Turn Division of Athletics and Recreation Community, Collection of Media Relations Photographs and Collection of Media Relations Documents into hyperlinks insteda of listing the URL after them. Consider simplifying the writing style. Does Alliance Digital Repository (ADR) have a website/page? Consider making Alliance Digital Repository (ADR) a hyperlink if so.
--

--

original message

Consider either changing the font or making the text black. (I know we're working towards AA, but this is an easy thing do do even better than AA). Remove underline from footer headers. Change header link to to go Library homepage, and add link to DU website on the footer.
--

**Comment by jrynhart** [comment]
"Can community and collections bolder words be turned into canned search links?"

This is part of task #279
