### ISSUE TITLE
loading message

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#282]
looking for solution to increase performance of site. Erin - should we have a loading message if something takes long to load? | Ooooh, if we could have a message, that would be great! "Patience is a virture. We promise your image is loading!" ;)
-- | --

**Comment by jrynhart** [comment]
33a10b91587cc314eba002d5567cf1e65fe12a2b
174a10d2a70a346d00e265624847e410f7e9be35
