### ISSUE TITLE
file image issue

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#283]
search for dog, result 4
http://libspecc01-vlp.du.edu/discovery/object/ba9126d0-fa40-441e-9999-63c416223db0#?c=&m=&s=&cv=&xywh=-4378%2C-336%2C13490%2C7223

issue with image not loading properly. file issue or size?

**Comment by jrynhart** [comment]
Image loads now, may have been fixed with a recent cantaloupe update.

Pre-cache, this image took maybe 15 seconds to load (it is big?)

http://libspecc01-vlp.du.edu/discovery/object/ba9126d0-fa40-441e-9999-63c416223db0#?c=&m=&s=&cv=&xywh=-6363%2C0%2C17461%2C6500
