### ISSUE TITLE
Collections view sort options

### ISSUE THREAD

**Issue by jrynhart** [dulibrarytech/digitaldu-frontend#293]
Add a sort option dropdown select box to the collection item view. Investigate default sort types for specific objects

Per Doug Rippey: “A default sort by archive call number is probably reliable, except in the case of certain P collections like Sets in Order where the ISO date in YYYYMMDD form follows the alphanumeric string of volume and issue designations. A default sort by filename within any given collection is another potential approach, again provided that the ISO date precedes the volume designation.”

**Comment by kcrowe1981** [comment]
I would actually recommend a default sort on date (either asc or des). No offense to Doug!

**Comment by kimpham54** [comment]
sort by title, also options to view 20/50/100 objects similar to search results
