### ISSUE TITLE
page for codu handles

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#303]
redirect all codu:* addresses to a handle error page with the message

Digital Collections @ DU has moved to an improved platform

 

Access the new website by using one of the buttons below. You will need to perform a keyword or advanced search to find the collection or object you are trying to view.

 

        [New Site] 

 

       [Advanced Search]

**Comment by jrynhart** [comment]
Created a page with a message and links to the speccoll.du.edu site and the advanced search page,
render upon receiving a pid of format "codu:n", (n = a number) in the /object route
