### ISSUE TITLE
iiif manifest validator doesn't know how to open the manifest

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#305]
manifests aren't validatin'

https://iiif.io/api/presentation/validator/service/validate?format=json&version=2.0&url=https://specialcollections.du.edu/iiif/72b8963c-8a3b-4483-9eb2-ad45878fcd3c/manifest

  "error": "Cannot fetch url. Got \"<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>\"",

want to use it with transkribus iiif manifest loader

IIIF is not valid (https://iiif.io/api/presentation/validator/service/) : Cannot fetch url. Got "<urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:852)>"

this happens with transkribus and the validator service. maybe an issue for IT to help us troubleshoot, an issue with server configuration

**Comment by jrynhart** [comment]
SSL issue has been fixed
Currently working on additional issues

**Comment by jrynhart** [comment]
Removed the empty (outer) thumbnail array until it is implemented

**Comment by jrynhart** [comment]
Added empty string to metadata object if a metadata field is not found or null

**Comment by jrynhart** [comment]
audio, video, pdf and image object manifests validate with no errors. There are warnings present
