### ISSUE TITLE
download button for screen reader

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#315]
from erin: Ohhhh. Yeah, the way the download button exists now requires an extra click fo the user, and might put things out of order for screen readers. It would be preferable to list the files available to download in a way similar to the Classon's example Doug provided above - there's no need to display a file name, but the example does include the file type which is important, and the file link displays at all time, not requiring an extra click. It makes sense to require the extra click fo the citations, because those take up a lot of space so you don't want them to display all the time. But the download is a single line, so my vote it to have it show always, with the rest of the metadata. 

best thing to do is to create a download button that directly downloads the item

**Comment by jrynhart** [comment]
Disabled the download link list section
Added link to download button that downloads the file directly
