### ISSUE TITLE
process to check public index for cache thumbnail

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#317]
Jeff will come up with route for delete thumbnail - Fernando suggesting worker process to detach us -> best thing to do is a service to check to delete thumbnails

**Comment by kimpham54** [comment]
automatic file checker to make sure cache exists in the index

**Comment by kimpham54** [comment]
replaces delete thumbnail route idea, maybe check weekly

**Comment by jrynhart** [comment]
Checks the public index for a record that corresponds to each item in the cache, and deletes the cache item if the index document is not present

Tests the DuraCloud object url (head request) and removes the cache item if the object is not available
