### ISSUE TITLE
collections or search results have additional filtering/limiting, for clarion

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#319]
[8:30 AM] Kristen Korfitzen
    
hi there, this might be a silly question but how do i set up page sub folders on the repository like the landing page in the Clarion Student Newspaper Records here: ttps://vpn-external.du.edu:443
​[8:30 AM] Kristen Korfitzen
    we previously had it so that the clarions was foldered by volume which we would like again, and in the division of athletics and recreation collection we had a different folders for images and publications. 
​[9:19 AM] Katherine Crowe
    Kim Pham I could be wrong, but I think we weren't going to do sub-folders if could use the dates to sort and browse more effectively, correct?
​[9:20 AM] Kristen Korfitzen
    well it wasn't very effective for sorting programs from images in the athletics collection but maybe that's because everything has item type still image and that's our fault. 
​[9:24 AM] Kristen Korfitzen
    in regards to the clarion I think that's fine if you know the exact date you want, but for students are looking to brows through "the 60s" that is going to be a problem
​[9:26 AM] Katherine Crowe
    Kim Pham and Jeff Rynhart (and maybe Erin Elzi) is this something we can take a look at together next week (with me and Kristen)?  I agree w Kristen that with a collection as large/extensive as the Clarions, limiting and date sorts within the collection are going to be critical.
(1 liked)​[9:49 AM] Kristen Korfitzen
    
on the collections page the only date sorting options is ascending/descending. https://specialcollections.du.edu/object/019d3890-7863-46a8-9d39-108a6ee489e1 is it possible to get the date slider put on those pages as well as the search in this collection results page? https://specialcollections.du.edu/search?field%5B%5D=all&q%5B%5D=clarion&f%5BCollection%5D%5B%5D=019d3890-7863-46a8-9d39-108a6ee489e1&type%5B%5D=contains&bool%5B%5D=or does that make sense?
<https://teams.microsoft.com/l/message/19:515deaa4462a49aa8cbca8700f082d9f@thread.skype/1593444607856?tenantId=6f3c7037-85c2-40e6-9dec-18b02d289288&amp;groupId=ee65c530-d295-4d1e-a7bb-adc1de59d3af&amp;parentMessageId=1593444607856&amp;teamName=University Libraries-g&amp;channelName=tech services digital collections&amp;createdTime=1593444607856>

**Comment by jrynhart** [comment]
#339
