### ISSUE TITLE
refactor code to combine search results and collection search view

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#322]
combine collection and search results faceting views rather than maintaining two separate

**Comment by jrynhart** [comment]
The views will stay separate, as the search results display metadata and the collection view does not

**Comment by jrynhart** [comment]
Updated the collection view controller to use the Search service, to have access to any data from that service. Removed the search function dedicated to the collection display. Added the daterange limiter functionality to the collection view controller.
