### ISSUE TITLE
digital object subjects browsing by subject

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#327]
e.g. an object with the subject jewish merchants would be clickable to show other objects with jewish merchants
https://specialcollections.du.edu/search?field%5B%5D=all&q%5B%5D=jewish+merchants&type%5B%5D=contains&bool%5B%5D=or&f%5BSubject%5D%5B%5D=Jewish%20merchants&expand%5B%5D=Subject

**Comment by jrynhart** [comment]
7e09b3cdca37b292aaf505318017e01ed30372b7
