### ISSUE TITLE
fix covillo collection - jp2s are actually tiffs 

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#329]
https://specialcollections.du.edu/object/f55b19b5-1279-470e-817d-1228353ac909

we used imagemagick to detect that the jp2s are actually tiffs, identify -verbose dip-store_f71f_c2c1_243e_4dae_8e40_3f89_9e15_79a6_f55b19b5-1279-470e-817d-1228353ac909_D022.02.0001.0008.00001_transfer-2eed3ead-ec08-4543-acdc-7b72c0a762c9_objects_db181633-c8e1-4222-b2ed-32843dd49bc4-D022.02.0001.0008.00001.jp2

(base) LIB-C02WT136HV2T:Desktop kimpham$ identify -verbose dip-store_f71f_c2c1_243e_4dae_8e40_3f89_9e15_79a6_f55b19b5-1279-470e-817d-1228353ac909_D022.02.0001.0008.00001_transfer-2eed3ead-ec08-4543-acdc-7b72c0a762c9_objects_db181633-c8e1-4222-b2ed-32843dd49bc4-D022.02.0001.0008.00001.jp2
Image: dip-store_f71f_c2c1_243e_4dae_8e40_3f89_9e15_79a6_f55b19b5-1279-470e-817d-1228353ac909_D022.02.0001.0008.00001_transfer-2eed3ead-ec08-4543-acdc-7b72c0a762c9_objects_db181633-c8e1-4222-b2ed-32843dd49bc4-D022.02.0001.0008.00001.jp2
  Format: TIFF (Tagged Image File Format)
  Mime type: image/tiff
  Class: DirectClass

**Comment by jrynhart** [comment]
Converted the tiffs to jp2 and uploaded to duracloud
