### ISSUE TITLE
additional facets and metadata display changes - Kate/Doug

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#338]
Preliminary recommendation about how both the left navigation “Browse By” menu should work and how the item catalog/display should look/behave.

 

Changes “Subjects” to “Topics” which should include all ASpace Subject “Term Types” (see: https://duarchstaff.coalliance.org/subjects > scroll down to “term type” in left navigation to see all term types in use/that can be applied)

·        Topical

·        Occupation

·        Names (People, Orgs, Buildings) – these come from “Agent” DB

·        Function

·        Temporal

·        Style/Period

·        Uniform Title

 

Add/Break out “Genre/Form” = ASpace Term Type “Genre/Form” (if we have a better/less jargon-y name, great. Also, maybe a mouseover explanation of “i.e. this IS a newspaper, not this is ABOUT newspapers” if Erin thinks it would be helpful/more “friendly”)

 

Places = ASpace Term Type “Geographic”

 

Modify “Browse By” in left navigation to mirror above item record display & behavior.

 

Example records that have most of these Subject term types:

·        Home of Abraham Jacobs:

o   Digital repository: https://specialcollections.du.edu/object/ea182cf0-0f0b-450d-b532-170588ed4937

o   ASpace: https://duarchstaff.coalliance.org/resources/1#tree::archival_object_68939

·        University of Denver Men’s Basketball Players:

 

A secondary and important question for DCS/SCA is – do we want to re-classify all subjects so that they are only either topic, genre/form, or geographic and eliminate use of all other term types at all levels (Resource & Item). If so, we should discuss/decide how that impacts repository changes & DCS/SCA work + related documentation.

 

A third consideration is the Alma integrations plugin; some of the manual changes to Subjects now recommended in documentation will not be necessary (or Doug doesn’t think so and will check).

**Comment by kimpham54** [comment]
all topics in subjects except geographic and genre, remove them from subjects without duplication
geographic and genre separate subjects fields
facet by geographic
facet by genre

**Comment by kimpham54** [comment]
4bfab145-9572-41f7-865f-3d00a309c26c  genre_form

**Comment by jrynhart** [comment]
Added the required subject "term types" to the "Topics" display field
Added a separate display field for the genre_form and geographic term types
