### ISSUE TITLE
special collections cantaloupe issue - white block again

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#347]
https://specialcollections.du.edu/object/9e09577b-9462-4875-ad3f-f1d9d7971844
same issue as before, probably should update cantaloupe. 
<img width="1161" alt="Screen Shot 2020-10-01 at 10 43 55 AM" src="https://user-images.githubusercontent.com/2915770/94838563-0615b200-03d3-11eb-87d0-b8c8660c8782.png">

**Comment by kimpham54** [comment]
future task to update to 4.1.7, the issue seemed to go away
https://github.com/cantaloupe-project/cantaloupe/issues/380

**Comment by jrynhart** [comment]
Updated to cantaloupe 4.1.7, white block issue appears to be gone

**Comment by jrynhart** [comment]
Updated to 4.1.7, white tile issue appears to be resolved
