### ISSUE TITLE
tabbing in firefox

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#355]
doesn't work

**Comment by jrynhart** [comment]
Tabbing is ok, but when a dropdown is selected, it can not be expanded with enter key press

**Comment by jrynhart** [comment]
Mozilla has a different hotkey to expand dropdown menus from select boxes, Alt+Dn Arrow
Will not update

**Comment by jrynhart** [comment]
Frontpage dropdown does not show selection when selected via tab, need to fix this
