### ISSUE TITLE
counter issue in search results

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#357]
"1 in 10 000" but there are more objects than 10 000

<img width="1181" alt="Screen Shot 2020-12-22 at 9 06 30 AM" src="https://user-images.githubusercontent.com/2915770/102908684-07d09e00-4435-11eb-8322-a575959bf5d1.png">

**Comment by jrynhart** [comment]
This is not a bug, view implementation truncates the search results total to 10000
This prevents accessing a page that is beyond the scope of the current Elastic configuration's ability 
Elastic needs further configuration to allow paging past 1000 (this is 10000 with the current frontend setting of 10 results per page)
