### ISSUE TITLE
too-fuzzy fuzzy search examples 

### ISSUE THREAD

**Issue by kcrowe1981** [dulibrarytech/digitaldu-frontend#409]
We will periodically come across very fuzzy search results that are sometimes so fuzzy as to be unclear how they were returned.

Ex: "lacrosse" limited by date 1960-1975. Includes several records that do not have the word "lacrosse" and it's unclear what in the record is returning the result.

https://specialcollections.du.edu/search?q%5B%5D=Lacrosse+&type%5B%5D=contains&bool%5B%5D=or&field%5B%5D=all&from=1960&to=1975&page=1

**Comment by jrynhart** [comment]
The unrelated results have "across" in the title, so the fuzziness is working on 2 locations in the search term. This may be the normal behavior of the fuzzy search. I'll take a closer look at it.

**Comment by kimpham54** [comment]
The LTS group discussed the issue - we tested it and it was expected behaviour, it would show precise results with 'lacrosse' first and then approximate results afterwards
