### ISSUE TITLE
Subject access term (Billie Stein's Harmony Girls Band) not pulling up search results despite being present in records

### ISSUE THREAD

**Issue by kcrowe1981** [dulibrarytech/digitaldu-frontend#413]
In looking for a specific image I noticed that this subject access term "Billie Stein's Harmony Girls Band," despite being present in two of the records, doesn't produce any results when it's clicked on.

Example images (both contain this subject access term): https://specialcollections.du.edu/object/d3dcaa18-d441-4396-9f0a-887e1277b279

⁠https://specialcollections.du.edu/object/fc62cf77-e03c-4f11-a625-e4fabcbd9a37.

I put this in Teams as a heads up in case anyone encounters something similar but this way you have it as a potential bug in your list.

**Comment by jrynhart** [comment]
related to issue #406
elastic should ignore punctuation in the index data

**Comment by jrynhart** [comment]
Fixed bug in search url sanitization that removed apostrophe but not the 's' character of possessive terms
