### ISSUE TITLE
facets aka limiter results

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#48]
•	When you go to the limiters from the first page (at the bottom left), the results just say * rather than the name of that limiter. It does say the limiter near the top, but it isn’t as clear as hearing it in the results page. Not sure if this can be changed.

**Comment by kimpham54** [comment]
Testing was done using the JAWS 2019.1810.64 - October 2018 release of Jaws Screen Reading Software.

**Comment by jrynhart** [comment]
Updated the "results" label string to show the facet name, if a facet is selected with no query string present, ie from the static front page facet list.
