### ISSUE TITLE
screen reader image loading message

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#50]
Testing was done using the JAWS 2019.1810.64 - October 2018 release of Jaws Screen Reading Software. 
•	Screen reader says “loading please wait” every time you open an item with an image, whether it’s loading or not.

**Comment by jrynhart** [comment]
Added an event handler to the OpenSeadragon viewer to remove the "loading..." message from the display upon the first tile load. It should no longer be present once the image starts loading

**Comment by jrynhart** [comment]
Is this a duplicate of issue #20?

**Comment by jrynhart** [comment]
Is this a duplicate of issue #19?

**Comment by kimpham54** [comment]
jeff and i tested using JAWS, even though the message is in the background it no longer says loading message
