### ISSUE TITLE
skipping in audio files

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#51]
Testing was done using the JAWS 2019.1810.64 - October 2018 release of Jaws Screen Reading Software. 

•	Can’t skip around in audio files. You can move around the time (although it doesn’t tell you where you are when you do) and then if you hit play, it goes back to wherever you were last listening
•	It does this without a screen reader as well!

**Comment by jrynhart** [comment]
This is likely due to the audio data being sourced from a stream rather than a file (It can not skip to a location downstream).  Tested the audio player with a file source, the time slider worked fine

**Comment by jrynhart** [comment]
We could cache the file locally to fix this

**Comment by kimpham54** [comment]
happens in chrome, not in firefox. will replace with kaltura. issue with chrome html player doesn't do progressive downloading

**Comment by kimpham54** [comment]
we are using kaltura, closing. consider testing with fallback video player if diff from in browser player
