### ISSUE TITLE
Display of 1-0 results needs to be fixed

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#54]
<img width="1354" alt="screen shot 2018-11-08 at 5 13 37 pm" src="https://user-images.githubusercontent.com/2915770/48235076-a98df180-e379-11e8-8269-98ab1a4633bf.png">
Quite a few times, a search would come up with “1-0 results”, which was confusing to users because they felt like something should have come up and they would try to see where that supposed one result was hiding.

**Comment by jrynhart** [comment]
Hid the pagination page display (n-n results) when there are no results.  Added a "no results found" message to the display when there are no search results.

**Comment by kimpham54** [comment]
this is done
