### ISSUE TITLE
facet text cutoff

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#57]
There was also an issue with trying to find sound recordings that were musical or nonmusical as the limiters under Type were cut off before you could read what type of sound recording it was.

**Comment by jrynhart** [comment]
This will be fixed when the index is corrected: Some 'sound recording' fields in the index contain data which need to be fixed.  These strings contain the text '[object,object]' in addition to the expected type value, and this is what is being truncated in the facet display.  Also, one record has the value 'sound recording,cassette tape,[object,object]' And this should be normalized to one of the existing sound recording types.

**Comment by kimpham54** [comment]
closing, index will change
