### ISSUE TITLE
Frontpage: change dropdown list to button element

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#62]
firefox doesn't render the dropdown list nicely. use a button element instead. see https://www.library.unt.edu/

**Comment by kimpham54** [comment]
nice to have. moving to backlog

**Comment by jrynhart** [comment]
The example at https://www.library.unt.edu/ is no longer valid
Placed a button element over the existing select element, disabled tab selection of button
Added select onchange function to update the button text when the select option is selected
