### ISSUE TITLE
download packages spec

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#77]
add spec to ingest structure doc https://docs.google.com/document/d/1lQcEt3_slGvSKYmw3hKKGtm9HiLsLEytdbC7oEI0xVo/edit?usp=sharing
download package of content + metadata + derivatives

**Comment by jrynhart** [comment]
image - file will be jp2 or jpg
audio - file will be mp3 from kaltura
video - file will be mp4 from kaltura
pdf - file will be pdf
compound - file will be a zip file of individuals (this applies for images and audio/video)

download file button
download metadata button (includes transcript)

**Comment by kimpham54** [comment]
kate: limit front end users to downloading derivative file, contact for master file. downloading metadata not a requirement.

**Comment by kimpham54** [comment]
if kaltura and cannot use api to download video, have popup in button that says you will be redirected to kaltura to download file
