### ISSUE TITLE
audio/video compound views using kaltura

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#79]
do some preliminary research on compound audio or videos or multi part videos and audios and how they can be displayed in kaltura as opposed to universalviewer. can you ingest audio or video sets of files into kaltura in the API? then can you bring back a playlist?

**Comment by jrynhart** [comment]
The Kaltura playlist (compound object) can be loaded in the same viewer as the single audio/video objects
