### ISSUE TITLE
some images not loading - maybe because jpeg?

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#83]
see https://specialcollections.du.edu/object/codu:70242
http://libspecc01-vlp.du.edu/discovery/object/codu:70242#?c=&m=&s=&cv=

it appears in fedora: http://librepo01-vlp.du.edu:8080/fedora/objects/codu:70242/datastreams/OBJ/content

**Comment by jrynhart** [comment]
Cantaloupe image server is not configured to retrieve JPG or OBJ datastreams from Fedora, so "small images" or jpg images can not be served via cantaloupe.   Will need to update the IIIF manifest to handle images that are not served by Cantaloupe server.

**Comment by kimpham54** [comment]
we're going to source jpgs and all other non tiff images directly from repository. cantaloupe only for tiffs

**Comment by kimpham54** [comment]
@jrynhart this should be finished, reference the commit where this change was made

**Comment by jrynhart** [comment]
bc1815fb0957869caebb4b33d54480daecb7daea

**Comment by kimpham54** [comment]
@jrynhart tested the links and it works now - thanks!
