### ISSUE TITLE
fallback viewer for audio/video?

### ISSUE THREAD

**Issue by kimpham54** [dulibrarytech/digitaldu-frontend#88]
should we have a fallback viewer for audio/video if kaltura doesn't work?

**Comment by kcrowe1981** [comment]
Do we have reason to think that Kaltura might not be in production by fall?

**Comment by josephlabrecque** [comment]
Kaltura is available now - unless I'm misunderstanding what is mean't . by "in production". Anyone at DU can use it, currently... it just isn't being heavily promoted until Summer/Autumn.

**Comment by kimpham54** [comment]
instead of fallback have error message, contact X for assistance

**Comment by kimpham54** [comment]
fallback viewer sources duracloud content, if content doesn't work (because 1gb and needs stitching, have a contact error message)

**Comment by jrynhart** [comment]
Backup viewers tested and functioning properly:

Audio: browser (html audio player), jwplayer, universalviewer (no kaltura embed)
Video: browser (html video player), videojs, jwplayer, universalviewer (no kaltura)
Images: openseadragon
Pdf: browser (html pdf viewer)

**Comment by jrynhart** [comment]
JWPlayer, videojs need style update to center the viewer on the object page

**Comment by kimpham54** [comment]
fallback viewer was also considered for other people to use alternative viewers. this is done now if kaltura is disabled have that option to use other videos. for us we need kaltura, progressive download vs streaming

**Comment by kimpham54** [comment]
code updated for means of streaming video or alternative viewers, ticket considered finished
